### DISCUSSION TITLE
Trying to setup server, Failed to connect to relay server

### DISCUSSION THREAD

**Discussion by dpolakovics** [rustdesk/rustdesk-server#353] [General]
Hello,

i try to setup the server for an NGO.
The Problem is i always get Failed to connect via relay server.

 - Install environment: docker (rustdesk/rustdesk-server:1) on nixos, both run on the same machine, and Ports are forwarded with docker
 - Also tried s6 image
 - Network 1st try: over VPN connection both connected via wireguard to opnsense.
 - Network 2nd try: made server public both connect via public ip
 - hbbs command: hbbs -r=....:21117
 - hbbr command: hbbr
 - Clients i just put the domain into the ID Server, also tried to put .....:21117 to relay server

I tried to debug it a bit. Connection to hbbs works good. I also get logging that the clients get an id and its stored into database.
Hbbr just gives standard startup log and then nothing more.
When trying with telnet i get connection refused on 21117,  because i wasn't sure if it uses ssl i also tried with openssl and also get refused. 21116 works fine.
Both Ports are opened and i can see them in netstat.

Best regards

**Comment by sebadamus** [comment]
In my case I had problems too with relay server, it was that my NAT router rule didnt work as it should with the server behind NAT, so had to change NAT rule for a HairPin NAT rule kind and now works right.

**Comment by pcarrick** [comment]
I had a similar issue. I hope this solution helps.

I setup Rustdesk server via docker and I could not get the relay to work properly. The error I continued to get was "Failed to connect via relay server". This turned out to be a network issue. I ended up finding some clues by looking at what docker had for networks. I changed the following in my compose.yml file

I could not simply specify the ports, but had to include the IP address. I also had to include the relay server name in the command line for the ID server.

```
services:
  hbbs:
    container_name: rustdesk-id
    image: rustdesk/rustdesk-server:latest
    environment:
      - ALWAYS_USE_RELAY=Y
    command: hbbs -r <RelayServerHostname>
    volumes:
      - ./data:/root
    ports:
      - "192.168.x.x:21115:21115"
      - "192.168.x.x:21116:21116"
      - "192.168.x.x:21116:21116/udp"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: rustdesk-relay
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    ports:
      - "192.168.x.x:21117:21117"
      - "192.168.x.x:21119:21119"
    restart: unless-stopped
```
