### DISCUSSION TITLE
Logs?

### DISCUSSION THREAD

**Discussion by y0d4a** [rustdesk/rustdesk-server#380] [General]
Hi, i would like just to log IP from where to where users doing connection (all is in LAN).
Now i see only logs like:

> INFO [src/rendezvous_server.rs:598] IP change of 474262042 from [::ffff:192.168.248.73]:59879 to [::ffff:192.168.248.197]:61005

But that IP is not real from users who do connection, what is the issue?

**Comment by GuillaumeHullin** [comment]
Based on the log you are showing, I'm guessing you are using RustDesk clients which are in the same LAN as your server... so it is normal to see local IP. If you place your server outside of your network, you will see public IP instead.

**Comment by y0d4a** [comment]
understand, but those IP are not from the clients which use rustdesk..

**Comment by GuillaumeHullin** [comment]
You are using Docker? Can you show your docker compose (without keys or secret of course) ?

**Comment by y0d4a** [comment]
yes, here it is:

> version: '3'
networks:
  rustdesk-net:
    external: false
services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r x.x.x.x:21117
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped
  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
  vector:
    image: timberio/vector:latest-alpine
    command: --config /etc/vector.toml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock     
      - /var/log/rustdesk:/var/log/rustdesk

**Reply by xlionjuan** [reply]
If you're using docker, your logs won't show on `/var/log/rustdesk`

**Reply by GuillaumeHullin** [reply]
Is there any logs stored inside the container that we could map?

**Comment by GuillaumeHullin** [comment]
Alright. And docker host is behind some firewall? This 192.168.248.x network... is your docker network? You can check with `docker network inspect rustdesk-net`

**Comment by y0d4a** [comment]
no, it is local lan

**Comment by GuillaumeHullin** [comment]
Ok but then I'm not sure to understand your problem... if your Rustdesk server is in the same LAN as your client... then it will show LAN IP.

**Comment by xlionjuan** [comment]
It is normal that Docker container can't see **Real IP** if you using Docker bridge network mode, please use `network_mode: host` instead, and clean all of your port setting.

```yml
version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r x.x.x.x:21117
    network_mode: host
    volumes:
      - ./data:/root
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    network_mode: host
    volumes:
      - ./data:/root
    restart: unless-stopped
```
