### DISCUSSION TITLE
P2P connection behind a Firewall

### DISCUSSION THREAD

**Discussion by GuillaumeHullin** [rustdesk/rustdesk-server#391] [Q&A]
I'm exploring how P2P connections work, especially with a RustDesk instance behind a pfSense firewall on a local network, with only standard ports forwarded.

I'm experimenting with NAT and will share updates. Any advice is welcome.

Below is the `docker-compose.yml` for RustDesk running on Debian:

```yaml
services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115       # NAT type test
      - 21116:21116       # TCP hole punching and connection service
      - 21116:21116/udp   # ID registration and heartbeat service
      - 21117:21117       # Relay services
    image: rustdesk/rustdesk-server-s6:latest
    environment:
      - RELAY
      - LIMIT_SPEED
      - TOTAL_BANDWIDTH
      - SINGLE_BANDWIDTH
      - ALWAYS_USE_RELAY
      - "ENCRYPTED_ONLY=1"
      - "RUST_LOG=info" # Debug level
    volumes:
      - /root/rustdesk/data:/data
    restart: unless-stopped
```

This setup is behind a pfSense firewall, with ports 21115-21117/tcp and 21116/udp forwarded to the Debian machine (no home router, pfSense is directly connected to the Internet).

Current observations:

- Two clients on the same LAN connect directly.
- A local client connecting to a remote one uses a relay connection.
- A VPN client connects directly to a LAN client if all traffic is via the VPN.
- A VPN client connects to a LAN client via relay if the VPN routes only LAN traffic.

My questions: how does the RustDesk server decide that P2P is possible... I'm guessing when he sees 2 client with the same public IP?

**Comment by GuillaumeHullin** [comment]
Alright, reading `rendezvous_server.rs` I understand that when both client are from the same public IP, then it is assumed that they are potentially reachable directly between them.

I found this which explains some:
https://github.com/rustdesk/rustdesk/wiki/How-does-RustDesk-work%3F

Also I'm not fully understanding what is the problem in not using `--net=host` in Docker.

I found this explanation: https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/
> --net=host only works on Linux, which makes hbbs/hbbr see the real incoming IP Address rather than the Container IP (172.17.0.1). If --net=host works fine, the -p options are not used. If on Windows, leave out sudo and --net=host.

But... with or without --net=host... my rendezvous_server sees the correct public IP addresses of the clients.
Also I figure that both of my clients are running behind an ISP router + pfSense ... so 2 NATs. So could be an extra difficulty.

I tried to dabble with Outbound NAT... without too much luck.

**Comment by xlionjuan** [comment]
You need `network_mode: host` to let application inside container see the **real IP**

**Reply by GuillaumeHullin** [reply]
From the logs of the container I can see that rustdesk sees the real IP... with or without `network_mode: host`

**Reply by GuillaumeHullin** [reply]
@xlionjuan sorry I have been away. I gave an other shot at this issue today.

Here was my docker compose:
```yaml
services:
  rustdesk-server:
    container_name: rustdesk-server
    # ports:
    #   - 21115:21115       # Server (NAT type test)
    #   - 21116:21116       # Server (TCP hole punching and connection service)
    #   - 21116:21116/udp   # Server (ID registration and heartbeat service)
    #   - 21117:21117       # Relay services
    network_mode: host
    image: rustdesk/rustdesk-server-s6:latest
    environment:
      - RELAY
      - LIMIT_SPEED
      - TOTAL_BANDWIDTH
      - SINGLE_BANDWIDTH
      - ALWAYS_USE_RELAY
      - "ENCRYPTED_ONLY=1"
      - "RUST_LOG=debug" # Set debug level (error|warn|info|debug|trace)
    volumes:
      - /srv/rustdesk/docker-data/data:/data
    restart: unless-stopped
```
    
Analysing the log I can see that the punch hole failed...
    
As a sidenote... I saw this https://github.com/rustdesk/rustdesk/discussions/6689
