### DISCUSSION TITLE
"Failed to connect via relay server: Failed to connect to relay server: Please try later"

### DISCUSSION THREAD

**Discussion by Californian** [rustdesk/rustdesk-server#396] [Q&A]
I'm trying to use my tablet as an external display. I came across rustdesk because Gnome's remote desktop feature doesn't seem to work, and deskreen was too tedious with the QR code every time. I don't have anything too crazy complex going on: simple home network (Nest Pro router/APs), static IP for my computer. I'm very experienced with docker-compose so I'm using that for my server.

It's possible my `docker-compose.yml` file is wrong, since I used the one from the repo instead of the docs (the compose yaml in the docs don't expose ports, so I assume those are just wrong and need fixing).

I'm on arch linux. I installed the `rustdesk-bin` package, ran it with `sudo`, changed the server settings to `localhost`/`localhost` and left the API server blank. It says "Ready" on the bottom.

On my tablet, I've installed the `rustdesk` app. I changed the server settings to my computer's local IP (192.168...) for relay and ID servers. My computer is definitely receiving a connection, since the docker compose logs show "New relay request" once it fails to connect (in the app it fails with the message `"Failed to connect via relay server: Failed to connect to relay server: Please try later"`).

Is there something I'm missing here? Love the project conceptually and I'm excited for the potential here, really hoping I can get this to work! Thanks in advance :slightly_smiling_face:

**Comment by pcarrick** [comment]
I had a similar issue. I hope this solution helps.

I setup Rustdesk server via docker and I could not get the relay to work properly. The error I continued to get was "Failed to connect via relay server". This turned out to be a network issue. I ended up finding some clues by looking at what docker had for networks. I changed the following in my compose.yml file

I could not simply specify the ports, but had to include the IP address. I also had to include the relay server name in the command line for the ID server. 

```
services:
  hbbs:
    container_name: rustdesk-id
    image: rustdesk/rustdesk-server:latest
    environment:
      - ALWAYS_USE_RELAY=Y
    command: hbbs -r <RelayServerHostname>
    volumes:
      - ./data:/root
    ports:
      - "192.168.x.x:21115:21115"
      - "192.168.x.x:21116:21116"
      - "192.168.x.x:21116:21116/udp"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: rustdesk-relay
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    ports:
      - "192.168.x.x:21117:21117"
      - "192.168.x.x:21119:21119"
    restart: unless-stopped
```
