### ISSUE TITLE
Timezone modification

### ISSUE THREAD

**Issue by jcorreajr** [rustdesk/rustdesk-server#115]
Hello
I needed to modify the Timezone in the containers to better follow the events in the LOGS.
The base image appears to be Ubuntu (see /etc/lsb_release file). To do this setup, I needed to install and reconfigure the 'tzdata' 
package. I had to make this adjustment in the command line, of the docker compose file. Details are below:

``
 command: bash -c "
         apt-get update && 
         apt-get install -yq tzdata && 
         ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && 
         dpkg-reconfigure -f noninteractive tzdata &&
         hbbs -r rustdesk.dominio.com.br:21117 -k _
       "
``

This causes a delay in creating containers, as it installs and reconfigures packages every time I have to recreate them.
I don't know if this would be the best practice, maybe the ideal would be for rustdesk to install the tzdata package in your images (rustdesk/rustdesk-server) what do you think?

**Comment by paspo** [comment]
First of all, you're better off by using UTC in all containers, then aggregate all logs on a single platform (graylog or similar) on which you can translate to any local time. It is very important to use a consistent time server-side, if you're dealing with different time zones, that's why UTC is used in almost all cases.

Now, to solve your problem: you can do it by altering the image directly on your server, in fact is very easy if you're using docker-compose. Take this simple `docker-compose.yaml` file:

```yaml
version: "3"

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk.dominio.com.br:21117 -k _ 
    restart: unless-stopped
    container_name: rustdesk-server
```

you can replace the `image:` part with a `build:` like this:

```yaml
version: "3"

services:
  hbbs:
    build: source
    command: hbbs -r rustdesk.dominio.com.br:21117 -k _ 
    restart: unless-stopped
    container_name: rustdesk-server
```

then create a `Dockerfile` inside a directory called `source`, with these contents:

```Dockerfile
FROM rustdesk/rustdesk-server:latest
RUN \
    echo "tzdata tzdata/Areas select America" | debconf-set-selections && \
    echo "tzdata tzdata/Zones/Europe select Sao_Paulo" | debconf-set-selections && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq tzdata
```

if you now start the container with `docker-compose up -d` the new image gets built (if it hasn't been built already) and started.

You can trigger a rebuild with `docker-compose up -d --build`
