### ISSUE TITLE
Possible solution for rustdesk-server-s6 on Armv7 and s6-overlay problem

### ISSUE THREAD

**Issue by ilsalgo** [rustdesk/rustdesk-server#125]
Hi, I tried to install Rustdesk server on my raspberry Pi3 with Raspian 32bit with Docker, I followed various guides but nothing worked in my machine.
The s6-overlay crashed for security reason e the container don't go up (restanting (111)).
I have found a solution by adding at the docker-compose file these lines:

> security_opt:
>       - seccomp:unconfined

With these lines the container go up and the server work fine.

**Comment by paspo** [comment]
Can you please post the full `docker-compose.yaml` file?
(you obviously have to redact the sensitive data)

**Comment by ilsalgo** [comment]
@paspo sure! 

version: '3'

services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: rustdesk/rustdesk-server-s6:latest-armv7
    environment:
      - "RELAY=MYIP.com:21117"
      - "ENCRYPTED_ONLY=0"
    volumes:
      - ./data:/data
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined

**Comment by paspo** [comment]
@ilsalgo I tried once again to reproduce your problem, without success.

- I used the `Raspberry Pi OS Lite` edition, downloaded from [here](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit) (so bullseye 32 bit)
- I installed docker following the [official instructions](https://docs.docker.com/engine/install/debian/)
- I used the exact `docker-compose.yaml` file you posted REMOVING the `security_opt` part (last 2 lines)
- `docker compose up -d` and the container is not crashing

```yaml
version: '3'

services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: rustdesk/rustdesk-server-s6:latest-armv7
    environment:
      - "RELAY=MYIP.com:21117"
      - "ENCRYPTED_ONLY=0"
    volumes:
      - ./data:/data
    restart: unless-stopped
```

What am I missing?
