### ISSUE TITLE
[Request] Docker support

### ISSUE THREAD

**Issue by schklom** [rustdesk/rustdesk-server#23]
Would you produce a Dockerfile and maintain it?
It would make it easier to run a server.

Ideally a Dockerfile for multiple platforms (or one for each). GitHub Actions make testing and publishing on DockerHub (or GitHub repo) easy: [multiple platform publishing](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md) and [testing](https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md)

----
EDIT: I am asking because the original issue (c.f. https://github.com/rustdesk/rustdesk-server/issues/4#issuecomment-831988770) links to a file that does not exist anymore: https://github.com/rustdesk/rustdesk-server/blob/master/id-relay-set.md#docker-example

**Comment by rustdesk** [comment]
Noted

**Comment by schleyk** [comment]
share my docker-compose.yml 😊


```
version: '3'

services:
  hbbs:
    image: rustdesk/rustdesk-server
    command: hbbs -r rustdesk.example.org:21117
    ports:
        - 21115:21115
        - 21116:21116
        - 21116:21116/udp
        - 21118:21118
    volumes:
      - ./data:/root
  hbbr:
    image: rustdesk/rustdesk-server
    command: hbbr
    ports:
        - 21117:21117
        - 21119:21119
    volumes:
      - ./data:/root
```
