### ISSUE TITLE
Allow keypair to be mounted as docker secrets

### ISSUE THREAD

**Issue by lonix1** [rustdesk/rustdesk-server#287]
## Is your feature request related to a problem? Please describe.
The self hosted docker option allows to mount the keypair as file mounts:
```yml
volumes:
  - ./id_ed25519:/data/id_ed25519:ro
  - ./id_ed25519.pub:/data/id_ed25519.pub:ro
```

Although this works, it's not ideal for such sensitive secrets.

## Describe the solution you'd like
Please consider allowing the keypair to be mounted as proper docker secrets:
```yml
secrets:
  secret_private:
    file: id_ed25519
  secret_public:
    file: id_ed25519.pub

services:
  rustdesk:
    secrets:
      - secret_private
      - secret_public
    image: rustdesk/rustdesk-server-s6:latest
    # ...
```

Those secrets would be automatically mounted at the standard docker paths:
```
/run/secrets/secret_private
/run/secrets/secret_public
```

Then the app can load the secrets from those files directly.

So from rustdesk's perspective, the ONLY change is to read from `/run/secrets/secret_private` and `/run/secrets/secret_public` instead of `/data/id_ed25519` and `/data/id_ed25519.pub`. That's it.

## Describe alternatives you've considered
Mounting as file mounts, as shown above.

## Additional context
Thanks for considering it.
