### ISSUE TITLE
self-host by myself is not free?

### ISSUE THREAD

**Issue by CListery** [rustdesk/rustdesk-server#32]
- docker-compose.yml
```
version: '3'

services:
  hbbs:
    image: rustdesk/rustdesk-server
    command: hbbs -r rustdesk.example.org:21117
    ports:
        - 21115:21115
        - 21116:21116
        - 21116:21116/udp
        - 21118:21118
    volumes:
      - ./data:/root
  hbbr:
    image: rustdesk/rustdesk-server
    command: hbbr
    ports:
        - 21117:21117
        - 21119:21119
    volumes:
      - ./data:/root
```

- logout
```log
Creating network "rustdesk_default" with the default driver
Creating rustdesk_hbbs_1 ... done
Creating rustdesk_hbbr_1 ... done
Attaching to rustdesk_hbbs_1, rustdesk_hbbr_1
hbbr_1  | [2022-06-09T03:27:33Z ERROR hbbr::lic] Registered email required (-m option). Please pay and register on https://rustdesk.com/server.
hbbs_1  | [2022-06-09T03:27:33Z ERROR hbbs::lic] Registered email required (-m option). Please pay and register on https://rustdesk.com/server.
rustdesk_hbbs_1 exited with code 0
rustdesk_hbbr_1 exited with code 0
```
