### ISSUE TITLE
unusable Docker container healthchecks

### ISSUE THREAD

**Issue by r4nchy** [rustdesk/rustdesk-server#490]
**Describe the bug**
Docker has this [guide ](https://docs.docker.com/reference/compose-file/services/#healthcheck) to use healthchecks to see if the containers are running smoothly or having errors, and many services depend on this data

**Describe the environment**
 - Install environment: docker
 - If available, the `docker-compose.yaml` file
```
services:
  hbbs:
    container_name: rustdesk-server-hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk-server.krn4hrj3.org:21117 -k _
    volumes:
      - /home/pi/data/rustdesk-server/data:/root
    network_mode: "host"
    depends_on:
      - hbbr
    # restart: unless-stopped
    labels:
      - sablier.enable=true
      - sablier.group=rustdesk


  hbbr:
    container_name: rustdesk-server-hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - /home/pi/data/rustdesk-server/data:/root
    network_mode: "host"
    # restart: unless-stopped
    labels:
      - sablier.enable=true
      - sablier.group=rustdesk


```
