### ISSUE TITLE
ERROR [libs/hbb_common/src/config.rs:538] Failed to store  config: Failed to create directory

### ISSUE THREAD

**Issue by truthsword** [rustdesk/rustdesk-server#526]
### Bug Description

I see this error in logs
`ERROR [libs/hbb_common/src/config.rs:538] Failed to store  config: Failed to create directory`

This is a simple LAN-only system. IPs are used to interconnect devices.

### How to Reproduce

docker compose up -d

### Expected Behavior

No error

### Operating system(s) on local (controlling) side and remote (controlled) side

Debian 12 server with Win 11 clients

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.38

### Screenshots

![](https://i.imgur.com/JtwkZaE.png)

### Additional Context

compose:
```
services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    restart: unless-stopped
    depends_on:
      - hbbr
    read_only: true
    security_opt:
      - no-new-privileges=true
    command: hbbs
    ports:
      - 21118:21118
    volumes:
      - data:/root

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges=true
    command: hbbr
    volumes:
      - data:/root
```

**Comment by nephrox** [comment]
So i just had the same error, i fixed it using "network_mode: "host", i also had an issue where i was running 2 instances of the server, where i installed a server not using docker that was running in the background and i forgot about, after uninstalling the non docker server and fixing the yml, it worked
 
<img width="492" height="502" alt="Image" src="https://github.com/user-attachments/assets/6f1aa581-9b2d-4b01-b509-2b20383dd0b6" />

**Comment by truthsword** [comment]
> i fixed it using "network_mode: "host"

Since you did that, you do not need to add the port-forwards in your yaml.

Instead, I trimmed things down to this since I'm not relaying:
```
services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    restart: unless-stopped
    depends_on:
      - hbbr
    read_only: true
    security_opt:
      - no-new-privileges=true
    command: hbbs
    ports:
      - 21118:21118
    volumes:
      - data:/root

volumes:
  data:
```
All is good.

**Comment by notgnu** [comment]
I created the /.config directory in the mounted volume (my own path) and set the appropriate folder permissions for the user with whom I started the container. After that, the message disappeared.

**Comment by Guiorgy** [comment]
From what I can tell from the [source code](https://github.com/rustdesk/hbb_common/blob/a86eda749e6fa33c282bab680e6b504d3ad87539/src/config.rs#L557), it tries to create a file named `RustDesk.toml`:

```rust
fn store_<T: serde::Serialize>(config: &T, suffix: &str) {
    let file = Self::file_(suffix); // `file_` appends the `suffix` to "RustDesk` and then applies the ".toml` extension
    if let Err(err) = store_path(file, config) { // see the function below
        log::error!("Failed to store {suffix} config: {err}"); // from the error log we know that `suffix` is an empty string here
    }
}

pub fn store_path<T: serde::Serialize>(path: PathBuf, cfg: T) -> crate::ResultType<()> {
    use std::os::unix::fs::PermissionsExt;
    Ok(confy::store_path_perms( // AFAIK, this creates config files inside ~/.config
        path,
        cfg,
        fs::Permissions::from_mode(0o600),
    )?)
}
```

Now, when setting the user the container should run as (e.g. `user: 1234:1234`), the home directory will point to the root `~/` -> `/`), thus the service attempts to create the config directory at the root (`/.config`) and fails. The simples workaround is to define the `HOME` environmental variable and set it to `/root`:

```yaml
hbbr:
    image: rustdesk/rustdesk-server:latest
    command: hbbr --key _
    restart: unless-stopped
    user: 1234:1234
    environment:
      HOME: /root
    networks:
      - network
    ports:
      - 21117:21117/tcp
      - 21119:21119/tcp
    volumes:
      - rustdesk_data:/root
```

Then the home directory gets resolved to `/root` instead, which is the mapped volume, so I am assuming you'd have set the correct permissions, and thus everything works fine, the `/root/.config/rustdesk/RustDesk.toml` is created.
