### ISSUE TITLE
Slow connection time

### ISSUE THREAD

**Issue by KreativeKrise** [rustdesk/rustdesk-server#54]
If I want to connect to a remote system it takes 20-30 seconds. But mostly it timeouts after 30 seconds. Both systems are running Windows 10 with RustDesk 1.1.9.

RustDesk Server was installed via docker and docker-compose on a public available server.

I used this docker-compose config:

```
version: '3'

services:
  rustdesk-server:
    container_name: rustdesk-server
    network_mode: host
    image: rustdesk/rustdesk-server-s6:latest
    environment:
      - "RELAY=<PUBLIC_IP>:21117"
      - "ENCRYPTED_ONLY=1"
    volumes:
      - ./data:/data
    restart: unless-stopped
```

but I also tried:

```
version: '3'

services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: rustdesk/rustdesk-server-s6:latest
    environment:
      - "RELAY=<PUBLIC_IP>:21117"
      - "ENCRYPTED_ONLY=1"
    volumes:
      - ./data:/data
    restart: unless-stopped
```

Ports 21115-21119/tcp and 21116/udp for incoming connections are open.

Any idea what could cause this long time it needs to connect?
